jobs:
  build:
    docker:
      - image: circleci/node:12.0
    steps:
      - checkout
      - run: echo 'build successfully'
  test:
    docker:
      - image: circleci/node:12.0
    steps:
      - checkout
      - run: npm install
workflows:
  version: 2
  build-n-deploy:
    jobs:
      - build:
          branches:
            only:
              - release
      - test


