version: 2.1

jobs:
  test:
    docker:
      - image: circleci/node:12.0
    steps:
      - checkout
      - run: npm install
  build:
    docker:
      - image: circleci/node:12.0
    steps:
      - checkout
      - run: echo "build successful! "

workflows:
  version: 2.1
    jobs:
      test:
        filters:
          branches:
            only:
              - master


