version: 2
jobs:
  test:
    docker:
      - image: circleci/node:12.0
    steps:
      - checkout
      - run: mkdir -p ./workspace
      - run: npm install
      - run: npm run test-coverage
      - run: npm test
      - store_artifacts:
          path: coverage
      - store_test_results:
          path: ./test-results
      - persist_to_workspace:
          root: ./workspace
          paths:
            - ./test-results/report.xml

  build:
    docker:
      - image: circleci/node:12.0
    steps:
      - checkout
      - run: echo 'build successfully'
      - attach_workspace:
          at: ./workspace
      - run: cd ./workspace
      - run: ls
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test


