cache-key: &cache-key dependency-cache-{{ checksum "package.json" }}
version: 2
jobs:
  test:
    docker:
      - image: circleci/node:12.0
    working_directory: ~/main
    steps:
      - checkout
      - run: mkdir -p ./workspace
      - run: npm install
      - restore_cache:
          keys:
            - *cache-key
      - save_cache:
          key: *cache-key
          paths:
            - ./node_modules
      - run: npm run test-coverage
      - run: npm test
      - store_artifacts:
          path: coverage
      - store_test_results:
          path: ./test-results
      - persist_to_workspace:
          root: ~/main/test-results
          paths:
            - report.xml

  build:
    docker:
      - image: circleci/node:12.0
    steps:
      - checkout
      - run: echo 'build successfully!'
      - attach_workspace:
          at: ~/main/test-results
      - run: ls ~/main/test-results
workflows:
  version: 2
  build_and_test:
    jobs:
      - test
      - build:
          requires:
              - test


