jobs:
  build:
    docker:
      - image: circleci/node:12.0
    steps:
      - checkout
      - run: echo 'build successfully'
  test:
    docker:
      - image: circleci/node:12.0
    steps:
      - checkout
      - run: npm install
      - run: npm test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test


