version: 2
jobs:
  test:
    working_directory: ~/repo
    docker:
      - image: circleci/node:12.0
    steps:
      - checkout
      - run: npm install
      - run: npm test
      - store_artifacts:
          path: test_report
  build:
    docker:
      - image: circleci/node:12.0
    steps:
      - checkout
      - run: echo 'build successfully'
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test


