version: 2.1

jobs:
  test:
    docker:
      - image: circleci/node:12.0
    steps:
      - checkout
      - run: npm install

workflows:
  version: 2.1
  filters:
    branches:
      only:
        - master
    jobs:
      - test

